name: amazon-paapi5-python-sdk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests>=2.28.0
  - aiohttp>=3.8.0
  - cachetools>=5.0.0
  - cryptography>=3.4.0
  - redis-py>=4.0.0
  - pytest>=7.0.0
  - pytest-asyncio>=0.18.0
  - flake8>=6.0.0